export const REGISTER_CUSTOMER = "REGISTER_CUSTOMER";
export const REGISTER_CUSTOMER_FAIL = "REGISTER_CUSTOMER_FAIL";
export const REGISTER_CUSTOMER_SUCCESS = "REGISTER_CUSTOMER_SUCCESS";
export const REGISTER_BRAND = "REGISTER_BRAND";
export const REGISTER_BRAND_FAIL = "REGISTER_BRAND_FAIL";
export const REGISTER_BRAND_SUCCESS = "REGISTER_BRAND_SUCCESS";
